# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/moettle/moettle.github.io"
[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/moettle_"
[social.params]
icon = "brand-twitter"


[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/moritz-oettle/"
[social.params]
icon = "brand-linkedin"


[[social]]
identifier = "rss"
name = "RSS"
url = "https://dfir-delight.de/index.xml"
[social.params]
icon = "rss"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:dfir-delight@proton.me"
[social.params]
icon = "email"